name: CI-CD
on:
  push:
    branches:
      - '**' # matches every branch

jobs:

  cache:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and check current crate
        run: cargo build && cargo check
      - name: Cache target folder
        id: cache-rust-crate
        uses: actions/cache@v3
        with:
          path: target/

  linting:
    needs:
      - cache
    runs-on: ubuntu-18.04
#    permissions:
#      contents: read
#      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install cargo clippy
        run: rustup component add clippy
#      - name: Install sarif components
#        run: cargo install clippy-sarif sarif-fmt
      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --tests -- -D warnings
        #continue-on-error: true
#      - name: Upload analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: rust-clippy-results.sarif
#          wait-for-processing: true

  test-with-coverage:
    needs:
      - cache
    runs-on: ubuntu-18.04
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.20.1'
          args: '-- --test-threads 1'
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml

  documentation:
    needs:
      - cache
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cargo doc
        run: cargo doc --all-features --no-deps
      - name: Archive generated documentation
        uses: actions/upload-artifact@v3
        with:
          name: project-documentation
          path: ./target/doc

  release:
    needs:
      - documentation
      - test-with-coverage
      - linting
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Setup semantic rust command
        run: cargo install semantic-release-rust --version 1.0.0-alpha.8
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}