name: CI-CD
on:
  push:
    branches:
      - develop

jobs:

  linting:
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cargo clippy
        run: rustup component add clippy

      - name: Install sarif components
        run: cargo install clippy-sarif sarif-fmt

      - name: Run cargo clippy
        run:
          cargo clippy
          --all-features
          --message-format=json --tests -- -D warnings | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  coverage:
    needs: linting
    runs-on: ubuntu-18.04
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.20.1'
          args: '-- --test-threads 1'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
