name: CI-CD
on:
  push:
    branches:
      - develop

jobs:

  checkout:
    name: checkout repository
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

  linting:
    needs: checkout
    name: linting rust code
    runs-on: ubuntu-18.04
    steps:
      - name: clippy tool
        uses: actions-rs/clippy-check@v1.0.7
