name: CI-CD
on:
  push:
    branches:
      - develop

jobs:

  analysis:
    runs-on: ubuntu-18.04
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Install cargo clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --tests -- -D warnings

      - name: Code coverage
        uses: actions-rs/tarpaulin@v0.1.0