name: CI-CD
on:
  push:
    branches:
      - develop

jobs:
  linting:
    name: linting rust code
    runs-on: ubuntu-18.04
    container: rust:latest
    steps:
      - name: clippy tool
        run: cargo clippy
